spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zq?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zhangqiang
  redis:
    cluster:
      nodes:
        - 192.168.56.211:31000
#        - 192.168.56.211:31001
#        - 192.168.56.211:31002
#        - 192.168.56.211:31100
#        - 192.168.56.211:31101
#        - 192.168.56.211:31102
      max-redirects: 100
    timeout: 2000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: -1
      cluster:
        refresh: # 注意要加上这段配置，否则故障转移后ip会变，如果不刷新会造成无法访问
          period: 300s
          adaptive: true
    password:
